---
- hosts: all
  #remote_user: username specified in /etc/ansible/hosts
  become: yes
  become_user: root

  tasks:
  # - name: Set authorized key, removing all the authorized key already set
  #   authorized_key:
  #    user: root
  #    key: '{{ item }}'
  #    state: present
  #    exclusive: True
  #   with_file:
  #    - public_keys/web-platform

  - name: update package repository
    command: apt-get update
    become: true

  - name: install the various packages we need
    action: >
      {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
    with_items:
      - git
      - python2.7
      - virtualenv
      - python-pip
      - unattended-upgrades
    become: true

  - name: Disallow password authentication
    lineinfile: dest=/etc/ssh/sshd_config
                regexp="^PasswordAuthentication"
                line="PasswordAuthentication no"
                state=present
    notify: Restart ssh

  - name: remove old repo
    command: "rm -rf /root/web-platform-tests"

  - name: checkout the web-platform-tests
    git:
      repo: 'https://github.com/w3c/web-platform-tests.git'
      dest: ~/web-platform-tests
      force: yes

  - name: make python virtualenv
    pip:
      name: virtualenv
      virtualenv: ~/web-platform-tests/_venv

  - name: make sure we can open enough files
    lineinfile: dest=/etc/systemd/system.conf
      regexp="DefaultLimitNOFILE"
      line="DefaultLimitNOFILE=65536"
      state=present

  - name: Update the hosts file
    shell: /root/web-platform-tests/wpt make-hosts-file | sed 's/web-platform.test/web-platform-tests.live/g' | sudo tee -a /etc/hosts
    become: true

  - name: ensure wpt service is configured
    template:
      src: files/wpt.service
      dest: /etc/systemd/system/

  - name: ensure config.json is in the correct location
    template:
      src: files/config.json
      dest: /root/web-platform-tests/

  - name: Enable the wpt service in systemd
    systemd:
      enabled: True
      name: wpt
      state: started

  - name: reboot the machine
    command: /sbin/shutdown -r +1
    async: 0
    poll: 0
    ignore_errors: true

  handlers:
    - name: Restart ssh
      service: name=ssh state=restarted


# outstanding things:
# add the run/running.ini -- problematic because we don't want to expose our
#                            API keys to the public. suggest we just do this
#			     manually for now.
#
# 


