---
- hosts: all
  become: yes
  become_user: root
  gather_facts: False

  tasks:
  - name: update package repository
    apt:
      update_cache: yes

  - name: install the various packages we need
    apt:
      name: "{{ packages }}"
    vars:
      packages:
        - git
        - python2.7
        - virtualenv
        - python-pip
        - unattended-upgrades

  - name: Disallow password authentication
    lineinfile: dest=/etc/ssh/sshd_config
                regexp="^PasswordAuthentication"
                line="PasswordAuthentication no"
                state=present
    notify: Restart ssh

  - name: checkout the web-platform-tests
    git:
      repo: 'https://github.com/web-platform-tests/wpt.git'
      dest: ~/web-platform-tests
      force: yes

  - name: make python virtualenv
    pip:
      name: virtualenv
      virtualenv: ~/web-platform-tests/_venv

  - name: Install WPT services
    copy:
      src: '{{item}}'
      dest: /etc/systemd/system/
    with_items:
      - files/wpt.service
      - files/wpt-sync.service
      - files/wpt-sync.timer

  - name: Install WPT synchronization script
    copy:
      src: files/sync-wpt.sh
      dest: /root/
      owner: root
      mode: '0700'

  - name: ensure config.json is in the correct location
    copy:
      src: files/config-{{ vagrant_provision | ternary("development", "production") }}.json
      dest: /root/web-platform-tests/config.json

  - name: Enable WPT services in systemd
    systemd:
      enabled: True
      name: '{{item}}'
      state: started
    with_items:
      - wpt
      - wpt-sync

  - include: certbot.yml
    when: not vagrant_provision

  # force_restart is false by default this can be set via the command line using --extra-vars
  # $ ansible-playbook playbook.yml --extra-vars "force_restart=true"
  - name: reboot the machine
    command: /sbin/shutdown -r +1
    async: 0
    poll: 0
    ignore_errors: true
    when: force_restart

  handlers:
    - name: Restart ssh
      service: name=ssh state=restarted
