---
- hosts: debian
  remote_user: root
  tasks:
  - name: install the various packages we need
    action: >
      {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
    with_items:
      - emacs-nox
      - htop
      - rsync
      - dtrx
      - git
      - libnss3-tools
      - python2.7
      - virtualenv
      - python-pip
      - screen
      - curl
      - xauth
      - xvfb
      - software-properties-common

  
  - name: checkout the wptdashboard project
    git: 
      repo: 'https://github.com/w3c/wptdashboard.git'
      dest: /root/wptdashboard
      
  - name: checkout the web-platform-tests
    git: 
      repo: 'https://github.com/w3c/web-platform-tests.git'
      dest: /root/web-platform-tests
      
  # https://cloud.google.com/sdk/docs/quickstart-debian-ubuntu