---
- hosts: debian
  #remote_user: root #admin on ec2 for debian
  become: yes
  become_user: root

  tasks:
  - name: Set authorized key, removing all the authorized key already set
    authorized_key:
     user: root
     key: '{{ item }}'
     state: present
     exclusive: True
    with_file:
     - public_keys/web-platform

  - name: make sure we have the GPG key for google cloud repo
    get_url:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        dest: /tmp/key.gpg

  - name: install key
    command: apt-key add /tmp/key.gpg
    become: true

  - name: make sure we have google cloud repo added
    lineinfile:
        path: /etc/apt/sources.list.d/google-cloud-sdk.list
        line: deb http://packages.cloud.google.com/apt cloud-sdk-stretch main
        create: true
    become: true

  - name: install nvidia drivers (for GPU machines)
    lineinfile:
        path: /etc/apt/sources.list.d/nvidia-drivers.list
        line: deb http://httpredir.debian.org/debian/ stretch main contrib non-free
        create: true
    become: true

  - name: update package repository
    command: apt-get update
    become: true

  #- name: install the kernel headers
  #  command: "shell apt-get install -y linux-headers-$(uname -r)"
  #  become: true

  - name: install the various packages we need
    action: >
      {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
    with_items:
      - emacs-nox
      - htop
      - rsync
      - dtrx
      - git
      - libnss3-tools
      - python2.7
      - virtualenv
      - python-pip
      - screen
      - curl
      - xauth
      - xvfb
      - google-cloud-sdk
      - linux-headers-amd64
      - nvidia-driver
    become: true

  - name: checkout the wptdashboard project
    git:
      repo: 'https://github.com/w3c/wptdashboard.git'
      dest: ~/wptdashboard

  - name: checkout the web-platform-tests
    git:
      repo: 'https://github.com/w3c/web-platform-tests.git'
      dest: ~/web-platform-tests

  - name: install python requirements
    pip:
      requirements: ~/wptdashboard/requirements.txt

  - name: make python virtualenv
    pip:
      name: virtualenv
      virtualenv: ~/web-platform-tests/_venv

  - name: make sure we can open enough files
    lineinfile: dest=/etc/systemd/system.conf
      regexp="DefaultLimitNOFILE"
      line="DefaultLimitNOFILE=65536"
      state=present

  - name: copy various files in /files/root/ to /root/
    copy:
      src: files/root/browser-runner.sh
      dest: /root/browser-runner.sh
      owner: root
      group: root
      mode: 0755

  - name: make a cronjob to run browser-runner.sh
    cron:
      name: "run browsers"
      minute: "*/1"
      job: "/root/browser-runner.sh > /root/browser-runner.log 2>&1"

  # - name: reboot the machine
  #   command: /sbin/shutdown -r +1
  #   async: 0
  #   poll: 0
  #   ignore_errors: true

# https://github.com/ansible/ansible/issues/10157


