---
- hosts: all
  become: yes
  become_user: root
  gather_facts: False

  tasks:
  - name: update package repository
    apt:
      update_cache: yes
    become: true

  - name: install the various packages we need
    apt:
      name: "{{ packages }}"
    vars:
      packages:
        - git
        - python2.7
        - virtualenv
        - python-pip
        - unattended-upgrades
    become: true

  - name: Disallow password authentication
    lineinfile: dest=/etc/ssh/sshd_config
                regexp="^PasswordAuthentication"
                line="PasswordAuthentication no"
                state=present
    notify: Restart ssh

  - name: remove old repo
    file:
      path: /root/web-platform-tests
      state: absent

  - name: checkout the web-platform-tests
    git:
      repo: 'https://github.com/w3c/web-platform-tests.git'
      dest: ~/web-platform-tests
      force: yes

  - name: make python virtualenv
    pip:
      name: virtualenv
      virtualenv: ~/web-platform-tests/_venv

  - name: make sure we can open enough files
    lineinfile: dest=/etc/systemd/system.conf
      regexp="DefaultLimitNOFILE"
      line="DefaultLimitNOFILE=65536"
      state=present

  - name: ensure wpt service is configured
    template:
      src: files/wpt.service
      dest: /etc/systemd/system/

  - name: ensure config.json is in the correct location
    template:
      src: files/config.json
      dest: /root/web-platform-tests/

  - name: Update the hosts file
    shell: /root/web-platform-tests/wpt make-hosts-file | sudo tee -a /etc/hosts
    become: true

  - name: Enable the wpt service in systemd
    systemd:
      enabled: True
      name: wpt
      state: started

  - include: certbot.yml
    when: inventory_hostname != 'vagrant'

  - name: Add cron job to sync wpt
    cron:
      name: Certbot automatic renewal.
      job: "cd /root/web-platform-tests/ && git pull origin master && systemctl restart wpt"
      minute: 0
      hour: 23

  - name: reboot the machine
    command: /sbin/shutdown -r +1
    async: 0
    poll: 0
    ignore_errors: true

  handlers:
    - name: Restart ssh
      service: name=ssh state=restarted
