---
- hosts: debian
  remote_user: root
  tasks:
  - name: install the various packages we need
    action: >
      {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
    with_items:
      - emacs-nox
      - htop
      - rsync
      - dtrx
      - git
      - libnss3-tools
      - python2.7
      - virtualenv
      - python-pip
      - screen
      - curl
  
  - name: checkout the wptdashboard project
    git: 
      repo: 'https://github.com/w3c/wptdashboard.git'
      dest: /root/wptdashboard
      
  - name: checkout the web-platform-tests
    git: 
      repo: 'https://github.com/w3c/web-platform-tests.git'
      dest: /root/web-platform-tests
      
  - name: check for the google cloud tools
    command: gcloud
    register: gcloud
    ignore_errors: True

  - name: install google cloud tools as we didn't find them
    command: "curl https://sdk.cloud.google.com | bash"
