---
- hosts: all
  become: yes
  become_user: root
  gather_facts: False

  tasks:
  - name: update package repository
    apt:
      update_cache: yes

  - name: install the various packages we need
    apt:
      name: "{{ packages }}"
    vars:
      packages:
        - git
        - python2.7
        - virtualenv
        - python-pip
        - unattended-upgrades

  - name:    Add Docker GPG key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg

  - name:    Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable

  - name:    Install Docker
    apt:
      name: docker-ce
      state: present
      update_cache: yes

  - name: Disallow password authentication
    lineinfile: dest=/etc/ssh/sshd_config
                regexp="^PasswordAuthentication"
                line="PasswordAuthentication no"
                state=present
    notify: Restart ssh

  - name: ensure wpt docker service is configured
    template:
      src: files/docker.wpt.service
      dest: /etc/systemd/system/

  - name: Enable the wpt service in systemd
    systemd:
      enabled: True
      name: docker.wpt
      state: started

  - include: certbot.yml
    when: not vagrant_provision

  - name: Add cron job to sync wpt
    cron:
      name: Redeploy a new docker service every minute
      job: "docker pull bmac/wpt && docker service update --image bmac/wpt:latest wpt-service"
      minute: "*"
  
  handlers:
    - name: Restart ssh
      service: name=ssh state=restarted
