# Use certbot to generate letsencrypt ssl certs. This will also set up a cron
# job that will ensure the certs are kept up-to-date.

- name: install certbot
  apt:
    name: certbot
    state: present

- name: ensure certbot well-known path exists
  file:
    path: "/var/www/web-platform-tests/.well-known"
    state: directory

- name: test if certificate is available
  stat:
    path: /etc/letsencrypt/live/{{fqdn}}/fullchain.pem
  register: cert_file

- name: Generate self-signed certificate
  shell: |
    set -e
    mkdir -p /etc/letsencrypt/live/{{fqdn}}
    openssl req -x509 -nodes -subj '/CN=web-platform-tests.live' -days 365 \
      -newkey rsa:4096 -sha256 \
      -keyout /etc/letsencrypt/live/{{fqdn}}/privkey.pem \
      -out /etc/letsencrypt/live/{{fqdn}}/fullchain.pem

    md5sum /etc/letsencrypt/live/{{fqdn}}/fullchain.pem > \
      /etc/letsencrypt/live/{{fqdn}}/fullchain.pem.md5sum

  when: cert_file.stat.exists == false

# CertBot runs as the root user. Enable the setgid flag to ensure that the
# www-data user can read the files it inserts into the directories reserved for
# TLS certificates.
- name: Allow application user to read certificate
  file:
    path: /etc/letsencrypt
    state: directory
    group: www-data
    mode: 2750
    recurse: true

- name: test if certbot has been initialized
  shell: md5sum --check /etc/letsencrypt/live/{{fqdn}}/fullchain.pem.md5sum
  ignore_errors: true
  register: cert_file_is_self_signed

- name: initialize certbot
  command: >
    certbot certonly
      --webroot
      --agree-tos
      --non-interactive
      {{ (env == 'production') | ternary('', '--test-cert') }}
      --email {{letsencrypt_email}}
      -w /var/www/web-platform-tests
      -d web-platform-tests.live
      -d not-web-platform-tests.live
      -d www.not-web-platform-tests.live
      -d www.web-platform-tests.live
      -d www.www.not-web-platform-tests.live
      -d www.www.web-platform-tests.live
      -d www.www1.not-web-platform-tests.live
      -d www.www1.web-platform-tests.live
      -d www.www2.not-web-platform-tests.live
      -d www.www2.web-platform-tests.live
      -d www.xn--lve-6lad.not-web-platform-tests.live
      -d www.xn--lve-6lad.web-platform-tests.live
      -d www.xn--n8j6ds53lwwkrqhv28a.not-web-platform-tests.live
      -d www.xn--n8j6ds53lwwkrqhv28a.web-platform-tests.live
      -d www1.not-web-platform-tests.live
      -d www1.web-platform-tests.live
      -d www1.www.not-web-platform-tests.live
      -d www1.www.web-platform-tests.live
      -d www1.www1.not-web-platform-tests.live
      -d www1.www1.web-platform-tests.live
      -d www1.www2.not-web-platform-tests.live
      -d www1.www2.web-platform-tests.live
      -d www1.xn--lve-6lad.not-web-platform-tests.live
      -d www1.xn--lve-6lad.web-platform-tests.live
      -d www1.xn--n8j6ds53lwwkrqhv28a.not-web-platform-tests.live
      -d www1.xn--n8j6ds53lwwkrqhv28a.web-platform-tests.live
      -d www2.not-web-platform-tests.live
      -d www2.web-platform-tests.live
      -d www2.www.not-web-platform-tests.live
      -d www2.www.web-platform-tests.live
      -d www2.www1.not-web-platform-tests.live
      -d www2.www1.web-platform-tests.live
      -d www2.www2.not-web-platform-tests.live
      -d www2.www2.web-platform-tests.live
      -d www2.xn--lve-6lad.not-web-platform-tests.live
      -d www2.xn--lve-6lad.web-platform-tests.live
      -d www2.xn--n8j6ds53lwwkrqhv28a.not-web-platform-tests.live
      -d www2.xn--n8j6ds53lwwkrqhv28a.web-platform-tests.live
      -d xn--lve-6lad.not-web-platform-tests.live
      -d xn--lve-6lad.web-platform-tests.live
      -d xn--lve-6lad.www.not-web-platform-tests.live
      -d xn--lve-6lad.www.web-platform-tests.live
      -d xn--lve-6lad.www1.not-web-platform-tests.live
      -d xn--lve-6lad.www1.web-platform-tests.live
      -d xn--lve-6lad.www2.not-web-platform-tests.live
      -d xn--lve-6lad.www2.web-platform-tests.live
      -d xn--lve-6lad.xn--lve-6lad.not-web-platform-tests.live
      -d xn--lve-6lad.xn--lve-6lad.web-platform-tests.live
      -d xn--lve-6lad.xn--n8j6ds53lwwkrqhv28a.not-web-platform-tests.live
      -d xn--lve-6lad.xn--n8j6ds53lwwkrqhv28a.web-platform-tests.live
      -d xn--n8j6ds53lwwkrqhv28a.not-web-platform-tests.live
      -d xn--n8j6ds53lwwkrqhv28a.web-platform-tests.live
      -d xn--n8j6ds53lwwkrqhv28a.www.not-web-platform-tests.live
      -d xn--n8j6ds53lwwkrqhv28a.www.web-platform-tests.live
      -d xn--n8j6ds53lwwkrqhv28a.www1.not-web-platform-tests.live
      -d xn--n8j6ds53lwwkrqhv28a.www1.web-platform-tests.live
      -d xn--n8j6ds53lwwkrqhv28a.www2.not-web-platform-tests.live
      -d xn--n8j6ds53lwwkrqhv28a.www2.web-platform-tests.live
      -d xn--n8j6ds53lwwkrqhv28a.xn--lve-6lad.not-web-platform-tests.live
      -d xn--n8j6ds53lwwkrqhv28a.xn--lve-6lad.web-platform-tests.live
      -d xn--n8j6ds53lwwkrqhv28a.xn--n8j6ds53lwwkrqhv28a.not-web-platform-tests.live
      -d xn--n8j6ds53lwwkrqhv28a.xn--n8j6ds53lwwkrqhv28a.web-platform-tests.live

  when: cert_file_is_self_signed.rc == 0

- name: Add cron job for cert renewal
  cron:
    name: Certbot automatic renewal.
    job: "/usr/bin/certbot renew --quiet --no-self-upgrade && systemctl restart wpt"
    minute: 0
    hour: 23
